In [1]:
import numpy as np

In [2]:
np.random.normal(1.75 , 0.2 , 1000)

array([1.86734906, 1.47014319, 1.63420466, 1.92107733, 1.85631846,
       1.90916253, 1.89208926, 1.85985584, 1.93303713, 1.83962514,
       1.66469062, 1.85948539, 1.39361877, 2.09780564, 2.15317404,
       1.78297893, 1.78044099, 1.51522186, 1.96473159, 1.76842247,
       1.71832809, 1.7975336 , 1.67455256, 1.7089755 , 1.507747  ,
       1.69652708, 1.89895749, 1.87794382, 1.74121585, 1.96898246,
       1.44306158, 1.5438544 , 1.78683114, 1.79415966, 1.66369252,
       1.79259822, 1.69708958, 1.75313402, 1.58525265, 1.60640875,
       1.67837407, 1.63365846, 1.85313704, 1.80140968, 1.71975539,
       1.78616833, 1.94448257, 2.00842499, 1.62990682, 1.51337786,
       1.83604353, 2.07090632, 1.79199426, 1.61990398, 1.69973657,
       1.49858144, 2.04469649, 1.44319729, 1.65415669, 1.47744363,
       1.84154721, 1.78642284, 1.46750979, 1.94601997, 1.33561303,
       1.47996234, 1.90630934, 1.68000656, 1.48262313, 2.04917823,
       1.96178502, 1.68642009, 1.57785894, 1.64264611, 2.01114

In [3]:
np.round(np.random.normal(1.75 , 0.2 , 1000) , 2)

array([1.92, 1.89, 2.01, 1.66, 2.09, 1.81, 1.57, 2.18, 1.57, 1.46, 1.81,
       1.85, 1.51, 1.78, 1.94, 2.06, 1.76, 1.86, 1.86, 1.69, 2.09, 1.72,
       1.81, 2.01, 1.68, 1.74, 1.65, 1.66, 1.54, 1.68, 1.72, 1.8 , 1.7 ,
       2.03, 1.82, 1.72, 1.83, 1.58, 1.49, 1.66, 1.59, 1.69, 1.45, 2.07,
       1.63, 1.54, 1.46, 1.55, 1.42, 1.68, 1.63, 1.95, 1.68, 1.82, 1.54,
       1.55, 1.47, 1.98, 1.76, 1.87, 1.78, 1.56, 2.02, 2.03, 1.5 , 1.9 ,
       1.68, 1.91, 1.78, 1.8 , 1.45, 1.84, 1.77, 1.86, 1.83, 2.04, 1.84,
       1.62, 1.86, 1.84, 1.82, 1.75, 1.72, 1.9 , 1.62, 1.76, 1.99, 1.81,
       1.97, 1.67, 1.7 , 1.94, 1.56, 1.65, 1.79, 1.53, 1.7 , 1.8 , 1.74,
       1.63, 1.93, 2.07, 1.48, 1.6 , 1.42, 1.58, 1.42, 1.74, 1.4 , 1.79,
       1.91, 1.73, 1.66, 1.92, 2.05, 2.17, 1.48, 1.78, 1.72, 1.6 , 1.73,
       1.87, 1.24, 1.76, 1.63, 2.05, 1.84, 1.91, 1.45, 1.91, 1.64, 1.91,
       1.73, 1.93, 1.8 , 1.49, 1.68, 2.02, 1.61, 1.77, 1.88, 1.82, 2.15,
       1.58, 1.95, 1.67, 1.88, 1.94, 1.72, 1.48, 1.

In [4]:
height = np.round(np.random.normal(1.75 , 0.2 , 1000) , 2)
weight = np.round(np.random.normal(50 , 10 , 1000) , 2)

In [5]:
person = np.column_stack((height , weight))

In [6]:
person

array([[ 1.72, 52.48],
       [ 1.8 , 57.05],
       [ 1.89, 63.43],
       ...,
       [ 1.63, 43.39],
       [ 1.99, 48.17],
       [ 1.67, 53.42]])

In [7]:
'''
This code helps us to create random numpy arrays and how can we make multi dimensional numpy arrays
'''

'\nThis code helps us to create random numpy arrays and how can we make multi dimensional numpy arrays\n'